# Generated by Django 6.0 on 2025-12-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovation',
            name='development_process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='evidence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='evidence_attachment',
            field=models.FileField(blank=True, null=True, upload_to='innovations/evidence/'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='financial_considerations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='implementation_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='intellectual_property',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='manufacturing_and_quality_control',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='marketing_and_distribution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='regulatory_compliance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='regulatory_documents',
            field=models.FileField(blank=True, null=True, upload_to='innovations/regulatory/'),
        ),
        migrations.AddField(
            model_name='innovation',
            name='stakeholder_engagement',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='innovation',
            name='technical_specifications',
            field=models.TextField(blank=True),
        ),
    ]
