# Generated by Django 6.0 on 2025-12-09 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('innovations', '0002_innovation_development_process_innovation_evidence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='innovation',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='category',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='score',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='submitter_area',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='submitter_email',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='submitter_name',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='submitter_organization',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='innovation',
            name='technical_specifications',
        ),
    ]
